### ISSUE TITLE
Does not include dependencies configured as "implementation"

### ISSUE THREAD

**Issue by MadhuvanthG** [LeviticusMB/gradle-one-jar#10]
Dependencies are _not_ included into the one-jar, if they are configured in `implementation` scope. However, it works correctly with `compile` scope, which is now deprecated in Gradle. 

I can provide an example if required, but it's very much straight-forward to reproduce this issue.

**Comment by LeviticusMB** [comment]
I've just published 1.1.0 which should hopefully work better with modern Gradle versions.
