### ISSUE TITLE
Gradle 4 support

### ISSUE THREAD

**Issue by nsoft** [LeviticusMB/gradle-one-jar#2]
Transfering this here because it's biting me. Maybe I'll look into it, but anyone else feel free of course... As it stands this version of the plugin is relatively happy in gradle 3, but I and evidently some others have hit this problem in gradle 4+

https://github.com/rholder/gradle-one-jar/issues/34

It looks like something is relying on a toString() somewhere and an object has changed to an object without a useful toString() implementation in 4.

**Comment by LeviticusMB** [comment]
Do you have an example that triggers this?

**Comment by LeviticusMB** [comment]
Closing. Reopen if this is still a problem.
