### ISSUE TITLE
Switch to Gradle 7.0 causes "unknown property 'runtime'"

### ISSUE THREAD

**Issue by hannesa2** [LeviticusMB/gradle-one-jar#6]
When I switch to Gradle 7.0 https://github.com/ytai/ioio/pull/250/files I run into a build error

### Current Behavior
I run into 
```
> Could not create task ':HelloIOIOConsole:distJar'.
   > Could not create task of type 'OneJar'.
      > Could not get unknown property 'runtime' for configuration container of type org.gradle.api.internal.artifacts.configurations.DefaultConfigurationContainer.
```

This is the causing block

```
plugins {
    id "com.github.onslip.gradle-one-jar" version "1.0.6"
}

task distJar(type: OneJar) {                              <--- This is the error line !
    mainClass = 'ioio.examples.hello_console.HelloIOIOConsole'
}
```

### Steps to Reproduce 
https://github.com/ytai/ioio/pull/250/files

### Environment

Here you see the error https://github.com/ytai/ioio/pull/250/checks?check_run_id=2340438978

**Comment by hannesa2** [comment]
This seems to be the reason https://github.com/gradle/gradle/issues/16823#issuecomment-819276895

**Comment by mathieuruellan** [comment]
@hannesa2  have found a workaround?

**Comment by hannesa2** [comment]
@mathieuruellan No
And I stopped here, because it's a dead repository. My pull requests, are lonesome untouched

**Comment by ShaneF67** [comment]
I hit this issue today as well

**Comment by hannesa2** [comment]
@mathieuruellan @ShaneF67  I made it work 
with this pull request https://github.com/ytai/ioio/pull/250 
especially with this commit https://github.com/ytai/ioio/pull/250/commits/08c6dd38a6e4c

It all based on my fork https://github.com/hannesa2/gradle-one-jar
