### ISSUE TITLE
Gradle 7+ compatibility

### ISSUE THREAD

**Issue by creckord** [LeviticusMB/gradle-one-jar#9]
gradle-one-jar with Gradle 7+ results in

```
   > Could not create task of type 'OneJar'.
      > Could not get unknown property 'runtime' for configuration container of type org.gradle.api.internal.artifacts.configurations.DefaultConfigurationContainer.
```

because Gradle [removed the 'runtime' configuration] after 6.x

It would be nice to have a version that works with current Gradle versions.

**Comment by LeviticusMB** [comment]
I've just published 1.1.0 which should hopefully work better with modern Gradle versions.
